# Generated by Django 4.0.5 on 2022-07-04 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('image', models.URLField(null=True)),
                ('date_published', models.DateTimeField()),
                ('date_modified', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.author')),
                ('tags', models.ManyToManyField(to='news.tag')),
            ],
            options={
                'ordering': ('-date_published', '-date_modified'),
            },
        ),
    ]
